import os

class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv('MAIN_DATABASE_URL')
    MONITORING_SQLALCHEMY_DATABASE_URI = os.getenv('MONITORING_DATABASE_URL')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SECRET_KEY = os.getenv('SECRET_KEY')
    SECURITY_PASSWORD_SALT = os.getenv('SECURITY_PASSWORD_SALT')