"""empty message

Revision ID: 31f48f41bdf8
Revises: bfac8df88a43
Create Date: 2025-04-02 22:17:10.382165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f48f41bdf8'
down_revision = 'bfac8df88a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('factory_id', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensor_type', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('equipment_id', sa.String(length=4), nullable=False))
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'])
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipment_id')
        batch_op.drop_column('unit')
        batch_op.drop_column('sensor_type')

    op.drop_table('equipment')
    # ### end Alembic commands ###
