"""empty message

Revision ID: bfac8df88a43
Revises: 
Create Date: 2025-03-23 22:57:27.277563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfac8df88a43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factory',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('device',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('factory_id', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chart',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('time_series', sa.JSON(), nullable=False),
    sa.Column('device_id', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart')
    op.drop_table('device')
    op.drop_table('factory')
    # ### end Alembic commands ###
