"""add gin index to time_series

Revision ID: c9fc604ec75e
Revises: 7301152fb71f
Create Date: 2025-06-08 13:34:59.006434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fc604ec75e'
down_revision = '7301152fb71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.create_index('ix_chart_time_series_gin', ['time_series'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.drop_index('ix_chart_time_series_gin', postgresql_using='gin')

    # ### end Alembic commands ###
